### PR TITLE
Update kinder-app.sln

### PR DESCRIPTION
**Pull request by rokash7**

### CODE REVIEW

**Comment by rokash7** [comment]
I have created KinderTests project but GitHub does not detect any changes in it. Will try to sort it out

**Comment by rokash7** [comment]
fixed

**Comment by JustasBan** [comment]
there is aggregateSumming method in items controller, could you try test it?

**Comment by JustasBan** [comment]
AggregateSuming takes a list of items (ItemDTO) and counts all KarmaPoints of these items

**Comment by rokash7** [comment]
> there is aggregateSumming method in items controller, could you try test it?

done

**Pull request merged**
